disabled_rules:
- identifier_name
- nesting
- function_parameter_count
- function_body_length
- trailing_whitespace
- type_name
- file_length
- type_body_length
- inclusive_language
- large_tuple
- empty_enum_arguments

opt_in_rules:
- control_statement
- empty_count
- trailing_newline
- colon
- comma

excluded:
- Package.swift
- ".build"
- docs
- img
- spec
- Project-Meta
- DerivedData

line_length:
- 222 # warning
- 223 # error

cyclomatic_complexity:
- 09 # warning
- 10 # error
